version: "3.7"

services:
  juridico-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: juridico-front
    restart: always
    ports:
      - "8080:8080"
    networks:
      - juridico_api_juridico-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
networks:
  juridico_api_juridico-network:
    external: false
